---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1280
  synced_folders:
    - [".", "/home/vagrant/.dotfiles"]

platforms:
  - name: fedora-26
  - name: ubuntu-14.04
  - name: ubuntu-16.04

provisioner:
  name: shell

suites:
  - name: default
    run_list:
    attributes:

transport:
  name: rsync
  ssh_key: ~/.vagrant.d/insecure_private_key
  username: vagrant

verifier:
  name: inspec
