source 'https://supermarket.chef.io'

metadata

cookbook 'apt'
cookbook 'docker'
cookbook 'poise-python'
cookbook 'yum'
cookbook 'vagrant'

group :integration do
  cookbook 'jbartko_dotfiles_test', path: 'test/integration/cookbooks/jbartko_dotfiles_test'
  cookbook 'sudo'   # required for Fedora 26
end
